# This is syslog server, which receives logs from client
---
version: "2.1"

networks:
  my-external-network:
    external: true

services:
  syslog:
    container_name: syslog
    hostname: syslog
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/config:/config
      - ./data/log:/var/log
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
    networks:
      - my-external-network
